# Generated by Django 5.2.7 on 2025-10-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_subscription_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
